config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Panel Administrativo del Sistema'
admin.site.index_title = 'Panel Administrativo'

urlpatterns = [
    path('django/admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('core.urls')),
    path('', include('eventos.urls')),
    path('', include('reservas.urls')),
    path('', include('socios.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.shortcuts import redirect
from django.urls import path

from core.views.admin.club.views import ClubFormView
from core.views.admin.estadistica.views import EstadisticaAdminView
from core.views.admin.index.views import IndexAdminView
from core.views.admin.persona.views import *
from core.views.user.index.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', IndexAdminView.as_view(), name='index_admin'),

    # URLs del club (administración)
    path('admin/club/', lambda request: redirect('admin-club-form', permanent=True), name='club'),
    path('admin/club/detalles/', ClubFormView.as_view(), name='admin-club-form'),

    # URLs de persona (administración)
    path('admin/personas/', lambda request: redirect('admin-persona-listado', permanent=True), name='admin-persona'),
    path('admin/personas/listado/', PersonaAdminListView.as_view(), name='admin-persona-listado'),
    path('admin/personas/crear/', PersonaAdminCreateView.as_view(), name='admin-persona-crear'),
    path('admin/personas/<int:pk>/editar/', PersonaAdminUpdateView.as_view(), name='admin-persona-editar'),

    path('admin/estadisticas/', EstadisticaAdminView.as_view(), name='admin-estadisticas'),
]

reservas/forms.py
import mercadopago
from django import forms
from django.db import transaction, ProgrammingError, OperationalError

from reservas.models import Reserva, HoraLaboral, Deporte, Parameters
from static.credentials import MercadoPagoCredentials

public_key = MercadoPagoCredentials.get_public_key()
access_token = MercadoPagoCredentials.get_access_token()
sdk = mercadopago.SDK(access_token)


class ReservaAdminForm(forms.ModelForm):
    """Formulario para crear una reserva."""
    HORAS = (
        ('00:00:00', '00:00 hs'),
        ('01:00:00', '01:00 hs'),
        ('02:00:00', '02:00 hs'),
        ('03:00:00', '03:00 hs'),
        ('04:00:00', '04:00 hs'),
        ('05:00:00', '05:00 hs'),
        ('06:00:00', '06:00 hs'),
        ('07:00:00', '07:00 hs'),
        ('08:00:00', '08:00 hs'),
        ('09:00:00', '09:00 hs'),
        ('10:00:00', '10:00 hs'),
        ('11:00:00', '11:00 hs'),
        ('12:00:00', '12:00 hs'),
        ('13:00:00', '13:00 hs'),
        ('14:00:00', '14:00 hs'),
        ('15:00:00', '15:00 hs'),
        ('16:00:00', '16:00 hs'),
        ('17:00:00', '17:00 hs'),
        ('18:00:00', '18:00 hs'),
        ('19:00:00', '19:00 hs'),
        ('20:00:00', '20:00 hs'),
        ('21:00:00', '21:00 hs'),
        ('22:00:00', '22:00 hs'),
        ('23:00:00', '23:00 hs'),
    )
    try:
        deporte = forms.ChoiceField(
            label='Deporte',
            choices=Deporte.objects.all().values_list('id', 'nombre'),
            widget=forms.Select()
        )
        # Campo forma de pago sean radio buttons
        forma_pago = forms.ChoiceField(
            label='Forma de pago',
            choices=Reserva.FORMA_PAGO,
            widget=forms.RadioSelect())
        # Campo hora un number input
        hora = forms.ChoiceField(
            label='Hora',
            choices=HORAS,
            widget=forms.Select())
        precio = forms.DecimalField(
            required=False,
            label='Precio',
            help_text='Si no se ingresa un precio, el sistema utilizará el precio definido en la cancha.',
            widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el precio (opcional)'}))
    except (ProgrammingError, OperationalError):
        pass

    def save(self, commit=True):
        reserva = super().save(commit=False)
        with transaction.atomic():
            reserva.expira = False if reserva.forma_pago == 1 else self.instance.expira
            if reserva.precio is None:
                reserva.precio = reserva.cancha.precio_luz if reserva.con_luz and reserva.cancha.precio_luz else reserva.cancha.precio
            reserva.save()
            if reserva.forma_pago == 2:
                preference_data = {
                    "items": [
                        {
                            "title": reserva.__str__(),
                            "quantity": 1,
                            "currency_id": "ARS",
                            "unit_price": float(reserva.precio),
                            "description": "Reserva de cancha {}".format(reserva.cancha.club)
                        }
                    ],
                    "payer": {
                        "name": reserva.nombre,
                        "email": reserva.email,
                    },
                    "statement_descriptor": "Reserva de cancha {}".format(reserva.cancha.club),
                    "excluded_payment_types": [
                        {
                            "id": "ticket"
                        }
                    ],
                    "installments": 1,
                    "binary_mode": True,
                    "expires": reserva.expira,
                    "expiration_date_from": reserva.created_at.isoformat(),
                    "expiration_date_to": reserva.get_expiration_date(),
                    "back_urls": {
                        "success": "http://127.0.0.1:8000/reservas/checkout/",
                        "failure": "http://127.0.0.1:8000/reservas/checkout/",
                    },
                    "auto_return": "approved",
                    "external_reference": str(reserva.pk),
                }
                try:
                    preference_response = sdk.preference().create(preference_data)
                except ConnectionError:
                    raise ConnectionError("Error al crear la preferencia de pago, revise las credenciales.")
                if preference_response["status"] == 400:
                    raise ConnectionError("Error al crear la preferencia de pago, revise las credenciales.")
                preference = preference_response["response"]
                reserva.preference_id = preference["id"]
                reserva.save()
        return reserva

    class Meta:
        model = Reserva
        fields = ['cancha', 'nombre', 'email', 'fecha', 'hora', 'nota', 'forma_pago', 'con_luz', 'expira', 'precio']
        widgets = {
            'cancha': forms.Select(attrs={'disabled': True}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el email'}),
            'fecha': forms.DateInput(attrs={'class': 'form-control'}),
            'nota': forms.Textarea(attrs={'class': 'form-control', 'rows': 3,
                                          'placeholder': 'Ingrese una nota (opcional)'}),
            'con_luz': forms.CheckboxInput(),
            'expira': forms.CheckboxInput(),
            'precio': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el precio'}),
        }


class ReservaIndexForm(forms.Form):
    """Formulario para crear una reserva. Se usa en el index para que el usuario pueda elegir la cancha."""
    try:
        deporte = forms.ChoiceField(
            label='Deporte',
            required=True,
            choices=Deporte.objects.all().values_list('id', 'nombre'),
            widget=forms.Select()
        )
        fecha = forms.DateField(
            required=True,
            label='Fecha',
            widget=forms.DateInput(
                attrs={'class': 'form-control'}))
        hora = forms.ChoiceField(
            required=True,
            label='Hora',
            choices=HoraLaboral.objects.all().values_list('hora', 'hora'),
            widget=forms.Select()
        )
    except (ProgrammingError, OperationalError):
        pass


class ReservaUserForm(forms.ModelForm):
    """Formulario para crear una reserva. Se usa en el index para que el usuario pueda elegir la cancha."""
    try:
        deporte = forms.ChoiceField(
            label='Deporte',
            choices=Deporte.objects.all().values_list('id', 'nombre'),
            widget=forms.Select()
        )
        hora = forms.ChoiceField(
            label='Hora',
            choices=HoraLaboral.objects.all().values_list('hora', 'hora'),
            widget=forms.Select()
        )
    except (ProgrammingError, OperationalError):
        pass

    def save(self, commit=True):
        reserva = super().save(commit=False)
        with transaction.atomic():
            hora_laboral = HoraLaboral.objects.get(hora=self.cleaned_data['hora'])
            reserva.con_luz = reserva.cancha.canchahoralaboral_set.get(hora_laboral=hora_laboral).con_luz
            reserva.precio = reserva.cancha.precio_luz if reserva.con_luz and reserva.cancha.precio_luz else reserva.cancha.precio
            reserva.forma_pago = 2
            if commit:
                reserva.save()
                preference_data = {
                    "items": [
                        {
                            "title": reserva.__str__(),
                            "quantity": 1,
                            "currency_id": "ARS",
                            "unit_price": float(reserva.precio),
                            "description": "Reserva de cancha {}".format(reserva.cancha.club)
                        }
                    ],
                    "payer": {
                        "name": reserva.nombre,
                        "email": reserva.email,
                    },
                    "statement_descriptor": "Reserva de cancha {}".format(reserva.cancha.club),
                    "excluded_payment_types": [
                        {
                            "id": "ticket"
                        }
                    ],
                    "installments": 1,
                    "binary_mode": True,
                    "expires": True,
                    "expiration_date_from": reserva.created_at.isoformat(),
                    "expiration_date_to": reserva.get_expiration_date(),
                    "back_urls": {
                        "success": "http://127.0.0.1:8000/reservas/checkout/",
                        "failure": "http://127.0.0.1:8000/reservas/checkout/",
                    },
                    "auto_return": "approved",
                    "external_reference": str(reserva.pk),
                }
                try:
                    preference_response = sdk.preference().create(preference_data)
                except ConnectionError:
                    raise ConnectionError("Error al crear la preferencia de pago, revise las credenciales.")
                if preference_response["status"] == 400:
                    raise ConnectionError("Error al crear la preferencia de pago, revise las credenciales.")
                preference = preference_response["response"]
                reserva.preference_id = preference["id"]
                reserva.save()
        return reserva

    def clean(self):
        cleaned_data = self.cleaned_data
        max_reservas_user = Parameters.objects.get(pk=1).max_reservas_user
        reservas = Reserva.objects.filter(email=self.data.get('email'))
        count = 0
        for reserva in reservas:
            if not reserva.is_finished():
                count += 1
        if count >= max_reservas_user:

core/views/user/index/views.py
from datetime import datetime

from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView

from core.models import Club
from eventos.models import Evento
from reservas.forms import ReservaIndexForm


class IndexView(TemplateView):
    """Vista para la página de inicio."""
    template_name = 'pages/user/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Inicio'
        context['club_logo'] = Club.objects.get(pk=1).get_imagen()
        context['reserva_form'] = ReservaIndexForm()
        eventos = []
        for e in Evento.objects.filter(fecha_inicio__gte=datetime.now().date()).order_by('fecha_inicio'):
            eventos.append(e) if e.get_start_datetime() > datetime.now() else None
        context['eventos'] = eventos[:5]
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        if request.method == 'POST':
            data['deporte'] = request.POST.get('deporte')
            data['fecha'] = request.POST.get('fecha')
            data['hora'] = request.POST.get('hora')
            return redirect(reverse('reservas-crear') + '?fecha=' + data['fecha'] + '&hora=' + data['hora'] +
                            '&deporte=' + data['deporte'])

templates/pages/user/index.html
{% extends 'extends/user/base.html' %}
{% load static %}

{% block head_css %}
    <style>
        @media (max-width: 576px) {
            .label-align {
                text-align: left;
            }
        }

        @media (min-width: 576px) {
            .label-align {
                text-align: right;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Reservas</h3>
                    </div>
                    <form id="reserva_form" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="id_deporte" class="col-form-label col-md-3 col-sm-3 label-align">
                                    {{ reserva_form.deporte.label }} <span class="text-danger">*</span></label>
                                <div class="col-sm-7">
                                    {{ reserva_form.deporte }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_fecha" class="col-form-label col-md-3 col-sm-3 label-align">
                                    {{ reserva_form.fecha.label }} <span class="text-danger">*</span></label>
                                <div class="col-sm-7">
                                    <div class="input-group" id="div_id_fecha"
                                         data-target-input="nearest">
                                        {{ reserva_form.fecha }}
                                        <div class="input-group-append" data-target="#id_fecha"
                                             data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_hora" class="col-form-label col-md-3 col-sm-3 label-align">
                                    {{ reserva_form.hora.label }} <span class="text-danger">*</span></label>
                                <div class="col-sm-7">
                                    {{ reserva_form.hora }}
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success float-right">Ver Disponibilidad</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Eventos</h3>
                    </div>
                    <div class="card-body">
                        <!-- Lista de eventos -->
                        <div class="d-flex justify-content-center row">
                            <div class="col-md-10">
                                {% if not eventos %}
                                    <div class="alert alert-info" role="alert">
                                        No hay eventos disponibles
                                    </div>
                                {% else %}
                                    {% for evento in eventos %}
                                        <div class="row p-2 border rounded mb-2" style="background-color: #DAECFF">
                                            <div class="col-sm-3 mt-1 mb-1">
                                                <img class="img-fluid rounded mx-auto d-block" alt="Imagen de evento"
                                                     src="{{ evento.get_imagen }}">
                                            </div>
                                            <div class="col-sm-6 mt-1">
                                                <h5>{{ evento.nombre }}</h5>
                                                <div class="d-flex flex-row">
                                                    <time datetime="{{ evento.get_start_datetime }}">
                                                        <i class="fas fa-calendar-alt mr-2"></i>{{ evento.get_start_datetime }}
                                                    </time>
                                                </div>
                                                <br>
                                                <p class="text-justify text-truncate">{{ evento.descripcion }}</p>
                                            </div>
                                            <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                                                <div class="d-flex flex-row align-items-center">
                                                    <h4 class="mr-1"><small>desde</small>
                                                        ${{ evento.get_ticket_variante_lower_price }}</h4>
                                                </div>
                                                <a href="{% url 'eventos-detalle' evento.pk %}"
                                                   class="btn btn-block btn-primary btn-sm">
                                                    <i class="fas fa-shopping-cart"></i> Detalle</a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    <div class="d-flex justify-content-center">
                                        <a href="{% url 'eventos-listado' %}" class="btn btn-primary">Ver todos</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block body_js %}
    <!-- Tempus Dominus -->
    <link href="{% static 'libs/tempusdominus-bootstrap-5.39/tempusdominus-bootstrap-4.min.css' %}" media="all"
          rel="stylesheet">
    <script src="{% static 'libs/tempusdominus-bootstrap-5.39/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'libs/tempusdominus-bootstrap-5.39/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script>
        let selectDeporte = $('#id_deporte');
        let selectCancha = $('#id_cancha');
        let inputFecha = $('#id_fecha');
        let selectHora = $('#id_hora');
        selectDeporte.select2({
            theme: 'bootstrap4',
            placeholder: 'Seleccione un deporte',
            allowClear: true,
            width: '100%',
            language: 'es',
            required: true,
        });
        selectCancha.select2({
            theme: 'bootstrap4',
            placeholder: 'Seleccione una cancha disponible',
            allowClear: true,
            width: '100%',
            language: 'es',
        });
        selectHora.select2({
            theme: 'bootstrap4',
            placeholder: 'Seleccione una hora',
            allowClear: true,
            width: '100%',
            language: 'es',
        });
        inputFecha.datetimepicker({
            "format": "L",
            "locale": "es-AR",
            "date": new Date(),
            "minDate": moment().startOf('day'),
            "maxDate": moment().add(2, 'weeks'),
        });
    </script>
{% endblock body_js %}